require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SystemsController do

  # This should return the minimal set of attributes required to create a valid
  # System. As you add validations to System, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all systems as @systems" do
      system = System.create! valid_attributes
      get :index
      assigns(:systems).should eq([system])
    end
  end

  describe "GET show" do
    it "assigns the requested system as @system" do
      system = System.create! valid_attributes
      get :show, :id => system.id.to_s
      assigns(:system).should eq(system)
    end
  end

  describe "GET new" do
    it "assigns a new system as @system" do
      get :new
      assigns(:system).should be_a_new(System)
    end
  end

  describe "GET edit" do
    it "assigns the requested system as @system" do
      system = System.create! valid_attributes
      get :edit, :id => system.id.to_s
      assigns(:system).should eq(system)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new System" do
        expect {
          post :create, :system => valid_attributes
        }.to change(System, :count).by(1)
      end

      it "assigns a newly created system as @system" do
        post :create, :system => valid_attributes
        assigns(:system).should be_a(System)
        assigns(:system).should be_persisted
      end

      it "redirects to the created system" do
        post :create, :system => valid_attributes
        response.should redirect_to(System.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved system as @system" do
        # Trigger the behavior that occurs when invalid params are submitted
        System.any_instance.stub(:save).and_return(false)
        post :create, :system => {}
        assigns(:system).should be_a_new(System)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        System.any_instance.stub(:save).and_return(false)
        post :create, :system => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested system" do
        system = System.create! valid_attributes
        # Assuming there are no other systems in the database, this
        # specifies that the System created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        System.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => system.id, :system => {'these' => 'params'}
      end

      it "assigns the requested system as @system" do
        system = System.create! valid_attributes
        put :update, :id => system.id, :system => valid_attributes
        assigns(:system).should eq(system)
      end

      it "redirects to the system" do
        system = System.create! valid_attributes
        put :update, :id => system.id, :system => valid_attributes
        response.should redirect_to(system)
      end
    end

    describe "with invalid params" do
      it "assigns the system as @system" do
        system = System.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        System.any_instance.stub(:save).and_return(false)
        put :update, :id => system.id.to_s, :system => {}
        assigns(:system).should eq(system)
      end

      it "re-renders the 'edit' template" do
        system = System.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        System.any_instance.stub(:save).and_return(false)
        put :update, :id => system.id.to_s, :system => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested system" do
      system = System.create! valid_attributes
      expect {
        delete :destroy, :id => system.id.to_s
      }.to change(System, :count).by(-1)
    end

    it "redirects to the systems list" do
      system = System.create! valid_attributes
      delete :destroy, :id => system.id.to_s
      response.should redirect_to(systems_url)
    end
  end

end
